#!/bin/bash


format="%.10i %.12P %.8j %.8u %.15a %.10T %.10M %.20S %.20V %.12l %.4C %.4D %.20R"
format="%.10i %.12P %.8j %.8u %.15a %.10T %.10M %.20S %.20V %.12l %.4C %.4D %.20N %.20r %.12Q"
format="%.10i %.12P %.8j %.8u %.15a %.10T %.10M %.20S %.20V %.12l %.4C %.4D %.20R %.12Q"
squeue $@ --format="$format" 



