---
title: "HPC Seminars"
output: 
   flexdashboard::flex_dashboard:
      orientation: rows
      vertical_layout: scroll
      smart: false
---

<script>
$(document).ready(function() {
  $('.navbar').remove();
  $('body').css('padding-top', '0px');
});
</script>
<style>
.navbar {
  background-color:#502D0E;
}
.navbar-brand {
color:white!important;
}
</style>

```{r setup, include=FALSE}
suppressMessages(library(tidyverse))
library(flexdashboard)
library(knitr)
library(plotly)
library(DT)

Attendance <- read_csv('training.csv') %>% filter(Count > 0 )
theme_set(theme_classic())
```

```{r}
# Number of Sessions
Sessions <- Attendance %>% group_by(Session,ID) %>% count()
Major <- Attendance %>% group_by(Department) %>% count()
Attendees <- Attendance %>% count()
Return <- Attendance %>% group_by(Name) %>% count()
```



Row
------------------------------------

### Total Sessions

```{r total_sessions}
valueBox(length(Sessions$Session), icon = "fa-users", color = "#502D0E")
```

###  Total Attendees

```{r total_attendees}
valueBox(Attendees$n, icon = "fa-users", color = "#502D0E")
```

###  Unique Attendees

```{r return_attendees}
valueBox(length(Return$Name), icon = "fa-users", color = "#502D0E")
```

###  Major/Department

```{r total_department}
valueBox(length(Major$Department), icon = "fa-users", color = "#502D0E")
```


Row 
-------------------------------------------------

### 

```{r}
Attendance %>% group_by(Status) %>% summarize(Total=sum(Count), Unique=sum(n_distinct(Name))) %>% kable()
```

### 

```{r}
Attendance %>% group_by(College) %>% summarize(Total=sum(Count), Unique=sum(n_distinct(Name))) %>% kable()
```

### 

```{r}
tmp1 <- Attendance %>% group_by(CY,ID) %>% summarize(Sessions=sum(n_distinct(Session))) %>% group_by('Year'=CY) %>% summarize(Sessions=sum(Sessions))
tmp2 <- Attendance %>% group_by('Year'=CY) %>% summarize(Total=sum(Count), Unique=sum(n_distinct(Name))) 
inner_join(tmp1,tmp2) %>% kable()
```

###

```{r}
Attendance %>% group_by(Session) %>% summarize(Offered=n_distinct(Semester),Attendee=sum(Count),Unique=sum(n_distinct(Name))) %>% arrange(-Offered) %>%
  mutate_if(is.character, str_replace_all, pattern = "Shell Basic", replacement = "Basic Shell Scripting") %>%
  mutate_if(is.character, str_replace_all, pattern = "Shell Advanced", replacement = "Advanced Shell Scripting") %>%
  mutate_if(is.character, str_replace_all, pattern = "Python OOP", replacement = "Python Object Oriented Programming") %>%
  mutate_if(is.character, str_replace_all, pattern = "RDM", replacement = "Research Data Management") %>%
  datatable(options = list(pageLength = 5, autoWidth = TRUE, dom='tip', scrollY = '200px'), , rownames = FALSE)
```
